### ISSUE TITLE
How to run the program to get the result from a image?

### ISSUE THREAD

**Issue by teemiik** [RubbaBoy/NewOCR#3]
Hello! I would like to know where the database is for storing the characters or you need to form it yourself, it is not clear from the code, you could a little
explain how to use this database?

**Comment by RubbaBoy** [comment]
Thanks for the issue, I am going to be adding a database description and full usage tutorial to the README very soon, probably today or tomorrow since right now, as you said, it's not very clear.

**Comment by teemiik** [comment]
@RubbaBoy I have dealt with the database, but now when you try to learn, it gives an error:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Do you want to train? yes/no
yes
Generating features...
Exception in thread "main" java.lang.NullPointerException
	at com.uddernetworks.newocr.OCRUtils.getDiagonal(OCRUtils.java:412)
	at com.uddernetworks.newocr.SearchCharacter.lambda$applySections$3(SearchCharacter.java:259)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.uddernetworks.newocr.SearchCharacter.applySections(SearchCharacter.java:259)
	at com.uddernetworks.newocr.OCRHandle.getLetterFrom(OCRHandle.java:515)
	at com.uddernetworks.newocr.OCRHandle.trainImage(OCRHandle.java:251)
	at com.uddernetworks.newocr.Main.run(Main.java:37)
	at com.uddernetworks.newocr.Main.main(Main.java:20)

Process finished with exit code 1

**Comment by RubbaBoy** [comment]
Are you making sure it's pointing to a valid training image? I just added a usage description and everything to the README, it may be of use to you https://github.com/RubbaBoy/NewOCR#using-it

**Comment by teemiik** [comment]
@RubbaBoy Yes, I did everything according to the instructions. But there is an error when loading "training.jpg" specified above.

**Comment by RubbaBoy** [comment]
@teemiik Try changing the example class to point to the absolute path of your training.png file rather than relative if you haven't done so already. Was this training image something you generated or the one straight from the repo?

Just for shits & giggles, try adding `System.setProperty("newocr.rewrite", "true");` to the very beginning of the main method, that may resolve some problems (Still have yet to put that in the README as well).

**Comment by teemiik** [comment]
@RubbaBoy I tried to use your "training.jpg" and its. System.setProperty("newocr.rewrite", "true"); didn't help. The error remains the same as at the beginning.

**Comment by teemiik** [comment]
@RubbaBoy You just need to check for null and the program runs without errors . Mistake in this place.

`public static List<Map.Entry<Integer, Integer>> getDiagonal(boolean[][] values, boolean increasing) {
        int topSize = 0;
        int topTrue = 0;
        int bottomSize = 0;
        int bottomTrue = 0;
        if (values != null) {
            double slope = (double) values.length / (double) values[0].length;

            List<Integer> yPositions = new ArrayList<>();

            for (int x = 0; x < values[0].length; x++) {
                double y = slope * x;
                if (increasing) y = values.length - y;
                yPositions.add((int) y);
            }

            for (int x = 0; x < values[0].length; x++) {
                int yPos = yPositions.get(x);
                for (int y = 0; y < values.length; y++) {
                    if (y < yPos) {
                        if (values[y][x]) bottomTrue++;
                        bottomSize++;
                    } else {
                        if (values[y][x]) topTrue++;
                        topSize++;
                    }
                }
            }
        }

        List<Map.Entry<Integer, Integer>> ret = new LinkedList<>();
        ret.add(new AbstractMap.SimpleEntry<>(topTrue, topSize));
        ret.add(new AbstractMap.SimpleEntry<>(bottomTrue, bottomSize));
        return ret;
    }`
